version: '3.3'

services:
  app:
    build:
      context: .
    ports:
      - 25000:25000
  postgres:
    image: postgres:latest
    environment:
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=myapp
    ports:
      - 5436:5432

